### ISSUE TITLE
Upgrades to grist-electron discontinued?

### ISSUE THREAD

**Issue by tetricky** [gristlabs/grist-electron#29]
I note that the electron build has now fallen some way behind the current grist-core version.

Is the intention to no longer maintain current versions?

Is it possible to build more up to date versions? How does one do so?

I find grist-electron very useful as a personal tool, and to develop databases for later deployment to grist-cloud. The version discrepancy is a problem on a number of levels. I may have to go to a cloud or self-hosted basis...but that has some problems/limitations. Not least surrounding cases with issues of data protection and unsuitability for cloud based development.

Thank you for what we have. Not in any way complaining, but seeking clarification in order to determine future direction.

**Comment by paulfitz** [comment]
You are right that the build has been falling behind. We're planning to rectify that very soon though, watch this space!

The general method to build a more up to date version is to update the `core` submodule. There may be changes to core that require small changes to the grist-electron code also. We will have someone working on this soon.

**Comment by paulfitz** [comment]
Update: @SleepyLeslie is working on it in https://github.com/gristlabs/grist-electron/pull/30

**Comment by paulfitz** [comment]
Grist document upgrading is solid and carefully tested, I would not anticipate that kind of problem.

**Comment by paulfitz** [comment]
> Thank you for the work on podman, by the way. I will be looking into that for possible hosting on NAS servers - docker is not something I'll use on them.

Understood. Hope we can sort out the sandboxing situation under podman.

**Comment by SleepyLeslie** [comment]
grist-electron v0.2.9 with grist-core v1.1.14 has been released.

**Comment by tetricky** [comment]
Thank you for the update. All seems to be working well from the user end.
