### ISSUE TITLE
Error message when trying to export table in XLSX [bug]

### ISSUE THREAD

**Issue by guilherme15990** [gristlabs/grist-electron#9]
When trying to export a table by going to `Share` > `Export XLSX`

![bug](https://github.com/gristlabs/grist-electron/assets/81936104/a9f08da9-47bc-433d-a8a1-248e60d54bdd)

Edition: Windows 10 Home Single Language
Version: 22H2
Installed on ‎07/‎12/‎2019
OS Build: 19045.3324
Experience: Windows Feature Experience Pack 1000.19041.1000.0

**Comment by paulfitz** [comment]
Thanks for reporting this! I've replicated the problem. Will post when I have a solution.

**Comment by paulfitz** [comment]
I have a solution in hand (https://github.com/gristlabs/grist-core/pull/646), will work on getting a new release to see if it works for you.

**Comment by paulfitz** [comment]
Hi @guilherme15990, I made a new release: https://github.com/gristlabs/grist-electron/releases/tag/v0.2.4 - if you have a chance, it'd be great if you could try it out and see if it fixes the problem for you.

**Comment by paulfitz** [comment]
Thanks @guilherme15990, looks like I messed things up badly, sorry. Looking into what has changed with pyodide.

**Comment by paulfitz** [comment]
I made a hopefully corrected release: https://github.com/gristlabs/grist-electron/releases/tag/v0.2.5 :crossed_fingers:

**Comment by guilherme15990** [comment]
Everything is working now
